config/routes.rb
Rails.application.routes.draw do
  resources :ponies

end

app/models/pony.rb
class Pony < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ponies_controller.rb
class PoniesController < ApplicationController

  before_action :set_pony, only: [:show, :edit, :update, :destroy]
  # respond_to :html, :js, :json

  # GET /ponies
  # GET /ponies.json
  def index

    @ponies = Pony.all
  end

  # GET /ponies/1
  # GET /ponies/1.json
  def show
    # @pony = Pony.find(params[:id])
  end

  # GET /ponies/new
  def new
    @pony = Pony.new
  end

  # GET /ponies/1/edit
  def edit

  end

  # POST /ponies
  # POST /ponies.json
  def create



    @pony = Pony.new(pony_params)
    if @pony.save
      # binding.pry



      redirect_to ponies_path


    end
    # respond_to do |format|
    #   if @pony.save
    #     format.html { redirect_to @pony, notice: 'Pony was successfully created.' }
    #     # format.json { render :show, status: :created, location: @pony }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @pony.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /ponies/1
  # PATCH/PUT /ponies/1.json
  def update
    flash[:notice] =  'successfully updated' if @pony.update(pony_params)
      # redirect_to ponies_path
      # respond_with (@pony)
      # format.json{ render :edit}
      respond_to do |format|
        format.js


      end
  

    # respond_to do |format|
    #   if @pony.update(pony_params)
    #     # format.html { redirect_to @pony, notice: 'Pony was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @pony }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @pony.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /ponies/1
  # DELETE /ponies/1.json
  def destroy
    # binding.pry
    @pony = Pony.find(params[:id])
    @pony.destroy



    # respond_to do |format|
    #   format.html { redirect_to ponies_url}
    #   format.json { head :no_content }
    #   format.js {render :layout => false }
    # end
  end

  private


    # Use callbacks to share common setup or constraints between actions.
    def set_pony


      @pony = Pony.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pony_params


      
      params.require(:pony).permit(:name, :profession)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ponies_helper.rb
module PoniesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ponies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/ponies/_edit.html.erb
<h1>Editing Pony</h1>

<%= render 'form' %>

<%= link_to 'Show', @pony %>
<%= link_to 'Back', ponies_path %>

app/views/ponies/_form.html.erb
<%= form_for(@pony, remote:true) do |f|  %>
  <% if @pony.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pony.errors.count, "error") %> prohibited this pony from being saved:</h2>

      <ul>
      <% @pony.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :profession %><br>
    <%= f.text_field :profession %>
  </div>
  <div class="actions">
    <%= f.submit  %>
  </div>
<% end %>

app/views/ponies/_new.html.erb
<h1>New Pony</h1>

<%= render 'form' %>

<%= link_to 'Back', ponies_path %>

app/views/ponies/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pony.name %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @pony.profession %>
</p>

<%= link_to 'Edit', edit_pony_path(@pony) %> |
<%= link_to 'Back', ponies_path %>

app/views/ponies/destroy.js.erb
$('.delete_pony').bind('ajax:success', function(){
	$(this).closest('tr').fadeOut();
});

app/views/ponies/edit.js.erb
$('#ajax_edit').append("<%= j render :partial=>"edit" %>");

app/views/ponies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ponies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Profession</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ponies.each do |pony| %>
      <tr>
        <td><%= pony.name %></td>
        <td><%= pony.profession %></td>
        <td><%= link_to 'Show', pony, remote: true %></td>
        <td><%= link_to 'Edit', edit_pony_path(pony), {remote: true} %></td>
        <td><%= link_to 'Destroy', pony, method: :delete, data: { confirm: 'Are you sure?' },
        :remote => true, :class =>'delete_pony'%></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pony', new_pony_path, remote: true %>

<div id = "ajax_edit"></div>
<div id = "ajax_show"></div>
<div id = "ajax_new"></div>
<%= link_to 'comments', comments_path %>

app/views/ponies/new.js.erb
$("#ajax_class").append("<%=j render :partial=>"new" %>");

app/views/ponies/show.js.erb
$('#ajax_show').append("<%=j render :partial=> "show" %>");

app/views/ponies/update.js.erb
alert('update called');
$('#ajax_edit').hide();